config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  # Путь для админки
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  # Пути для формы регистрации, входа и т.д.
  devise_for :users

  # в профиле юзера показываем его игры, на главной - список лучших игроков
  resources :users, only: %i[index show]

  resources :games, only: %i[create show] do
    # доп. методы ресурса:
    put 'help', on: :member # помощь зала
    put 'answer', on: :member # ответ на текущий вопрос
    put 'take_money', on: :member #  игрок берет деньги
  end

  # Ресурс в единственном числе - ВопросЫ
  # для загрузки админом сразу пачки вопросОВ
  resource :questions, only: %i[new create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Who wants to become a millionaire</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
</head>

<body class="d-flex flex-column min-vh-100">
<div class="navbar navbar-default navbar-static-top bg-secondary bg-gradient">
  <div class="container">
    <%= link_to 'Billionaire', root_path, class: 'navbar-brand text-white' %>
    <% if user_signed_in? %>
      <div class="navbar-form navbar-right d-flex">

        <% if current_user.is_admin? %>
          <%# Ссылка на админку %>
          <%= link_to 'Админка', rails_admin_path, class: 'btn navbar-btn btn-danger btn-xs' %>
          <%= link_to 'Залить новые вопросы', new_questions_path, class: 'btn navbar-btn btn-warning btn-xs' %>
        <% end %>


        <%= link_to content_tag(:span, "#{current_user.name} - #{number_to_currency current_user.balance}"),
                    user_path(current_user),
                    class: 'btn navbar-btn'
        %>
        <%= button_to 'Новая игра', games_path, class: 'btn navbar-btn btn-success btn-xs me-2' %>
        <%= button_to 'Выйти', destroy_user_session_path, method: :delete, class: 'btn btn-info btn-xs navbar-btn' %>
      </div>
    <% else %>
      <div class="navbar-form navbar-right">
        <%= link_to 'Войти', new_user_session_path, class: 'btn btn-primary' %>
        <%= link_to 'Зарегистрироваться', new_user_registration_path, class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>
<main class="flex-shrink-0">
  <div class="container">
    <% if flash[:notice].present? %>
      <div class="alert alert-success alert-dismissible fade show mt-4" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert].present? %>
      <div class="alert alert-danger alert-dismissible fade show mt-4" role="alert">
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
        <%= flash[:alert] %>
      </div>
    <% end %>
    <div class="row">
      <div class="col-lg-12 mt-3">
        <%= yield %>
      </div>
    </div>
  </div>
</main>
<footer class="mt-auto py-4 text-right bg-dark">
  <div class="container">
    <div>&copy;
      <%= link_to 'Mike Godunoff', 'https://github.com/Mike2022SPB', class: 'text-white' %> &mdash;
      <%= Time.now.year %>
    </div>
  </div>
</footer>
</body>
</html>